name:                conc-tree
version:             0.1.0.0
github:              "Abhiroop/conc-tree"
license:             BSD3
author:              "Abhiroop Sarkar"
maintainer:          "asiamgenius@gmail.com"
copyright:           "2018 Abhiroop Sarkar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         An implicitly parallel data structure

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  conc-tree-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -eventlog
    dependencies:
    - conc-tree

tests:
  conc-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - conc-tree
